//g++ -Wall -Werror -g -std=c++20 -o main.exe src/main.cpp -I C:\msys64\mingw64\include -L C:\msys64\mingw64\lib -lraylib -lopengl32 -lgdi32 -lwinmm -L. -lAustinUtils
#run g++ {
    -Wall
    -Werror
    -Wno-class-memaccess
    -g
    -std=c++20
    -o UIDesigner.exe
    UIDesigner.cpp
    -I C:\msys64\mingw64\include
    -L C:\msys64\mingw64\lib
    -lraylib
    -lopengl32
    -lgdi32
    -lwinmm
    -L.
    -lAustinUtils
}
UIDesigner